app:
  name: user-service
  env: local
  version: 1.0.0

server:
  host: localhost
  port: 8082
  ssl: false
  jwt_secret_key: test-secret
  csrf: false

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 123
  db_name: db
  ssl_mode: false

  rabbit_mq:
    url: amqp://guest:guest@localhost:5672/
    queue_name: user_queue




